---
title: "Manuscript"
author: "Salma Abdel-Raheem, Emily Nazario, Allison Payne"
format: html
editor: visual
---

## Paper Description

## Data Summary

Ozsanlav-Harris et al. 2023 plotted how Ireland sub-population counts and percentages of juvenile Greenland White Fronted Geese changed from 1983 to 2019 using annual census data. This team was specifically interested in understanding how population counts and reproduction changed with varying temperatures and precipitation. From this set of figures, they identified that the metapopulation has declined since 1999 but only one of the metapopulations has mirrored this trend.

The data provided by Ozsanlav-Harris et al. 2023 was saved as two CSV files. The CSV file for the entire metapopulation included the year the spring census was conducted, the whole population size estimate, and the counts per metapopulation. We then modified this original file so that the metapopulation data was in long format rather than in wide. The CSV file for the juveniles included the year and the percent juveniles for each metapopulation.

## Analysis Summary

## Results

## Discussion
