---
title: "Replication for Geese"
format: 
  html: 
    echo: false
editor: visual
bibliography: references.bib
---

## Replicating a metapopulation analysis

We are replicating [@ozsanlav2023differing], 'Differing drivers of decline within a migratory metapopulation has implications for future conservation'.

The paper's Github is [here](https://github.com/LukeOzsanlav/GWfGMetapopDemography).

The Zenodo repository is [here](https://zenodo.org/records/8116139).

**Paper description:** This paper looks at a metapopulation of Greenland White-fronted geese (*Albifrons flavrostris*). There are two subpopulations: a southerly and northerly. One subpopulation is doing worse than the other, and so this paper performed analyses on the metapopulation and compared them for each subpopulation.

**Key finding:** In figure 2, Ozsanlav-Harris et al., 2023 explore how winter population counts and percentagage of juveniles vary between 1983 and 2018. This paper explored how temperature and percipitation influence reproductive success in Greenland White Fronted Geese. Thus, through this figure, the authors could visualize how populations have declined over the course of the study period. This team then compared these changes in population size to environmental conditions.

Let's look through the dataaaaa \<3
