---
editor_options: 
  markdown: 
    wrap: 72
---

Read in the data.

```{r}

library(tidyverse)

pop_counts <- readRDS(here::here("data/outputs/pop_count.RDS"))

young_count <- readRDS(here::here("data/outputs/young_count_proc.RDS")) 
max_mp <- readRDS(here::here("data/outputs/max_metpop.RDS"))
```

```{r}
young_plot <- ggplot(young_count, aes(x = data_year, y = Perc_young)) + 
  geom_line(aes(x = data_year, y = roll_mean, color = Ringing.location), linewidth = 2) + 
  geom_line(aes(color = Ringing.location), alpha = 0.2, size = 1.5) + 
  scale_color_manual(values = c("dodgerblue3", "darkorange3")) + 
  geom_vline(aes(xintercept = max_mp), linetype = "dashed") + 
  theme_bw() + 
  theme(panel.grid = element_blank(), legend.position = "none") + 
  labs(color = "Populations", 
       x = "Year", 
       y = "Percentage of juveniles")

```

```{r} 
#| fig-width: 6
#| fig-height: 8

pop_plot <- pop_counts %>% 
  drop_na() %>% 
  ggplot(aes(x = spring, y = count)) + 
  geom_point(aes(color = site), color = "gray60") + 
  geom_line(aes(color = site), size = 1.5) + 
  scale_color_manual(values = c("dodgerblue3", "aquamarine4", "darkorange3")) + 
  geom_vline(aes(xintercept = max_mp), linetype = "dashed") + 
  theme_bw() + 
  theme(panel.grid = element_blank(), 
        legend.position = c(.83, .83), 
        legend.margin = margin(t = 0)) + 
  labs(color = "Populations", 
       x = "Year", 
       y = "Winter population count")

ggpubr::ggarrange(pop_plot, young_plot, ncol = 1, labels = "auto")

```
